In [ ]:
from local.torch_basics import *
from local.test import *
from local.data.all import *
from local.vision.core import *

In [ ]:
source = untar_data(URLs.MNIST_TINY)/'train'
items = get_image_files(source)
fn = items[0]
fn

PosixPath('/home/quantran/.fastai/data/mnist_tiny/train/7/9286.png')

In [ ]:
type(array(3))

numpy.ndarray

In [ ]:
def neg(x): return -x

In [ ]:
neg((1,2))

TypeError: bad operand type for unary -: 'tuple'

In [ ]:
neg(array((1,2)))

array([-1, -2])

# Transform decorator can make a function work in a flexible way (inputs with different type)

Class decorator

In [ ]:
@Transform
def neg(x): return -x

This @Transform looks like you gonna pass the func (neg) in ```__init__``` of class Transform

In [ ]:
# equivalent
def _neg(x): return -x
neg = Transform(_neg)

In [ ]:
neg((1,2)) # this is like calling encode function in Transform class

(-1, -2)

In [ ]:
img = load_image(fn)
img

In [ ]:
type(img)

PIL.Image.Image

In [ ]:
t = tensor(array(img))
t[12:14]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 164, 239,  26,   0,   0,   0,
           0,  96, 236,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  12,  47,   0,   0,   0,   0,
           0, 179, 235,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
neg(t[12:14]) # negative here doesn't really work, due to type uint8 doesn't allow negative number

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,  92,  17, 230,   0,   0,   0,
           0, 160,  20,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 244, 209,   0,   0,   0,   0,
           0,  77,  21,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
t2 = t.float()
neg(t2[12:14])

tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -164., -239.,
          -26.,   -0.,   -0.,   -0.,   -0.,  -96., -236.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,  -12.,  -47.,
           -0.,   -0.,   -0.,   -0.,   -0., -179., -235.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

# Normalization, type notation to work with tuple

In [ ]:
def norm(x,m,s): return (x-m)/s

In [ ]:
t[12:14]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0, 164, 239,  26,   0,   0,   0,
           0,  96, 236,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  12,  47,   0,   0,   0,   0,
           0, 179, 235,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
       dtype=torch.uint8)

In [ ]:
t = t2 # to float

In [ ]:
n_img = norm(t,127,50)
n_img[12:14]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
n_img.mean()

tensor(-2.2250)

In [ ]:
@Transform
def norm(x,m,s): return (x-m)/s

In [ ]:
tupl = (t,1) # assume a image t with label '1'
temp = norm(tupl,m=127,s=50) # need keywords for @Transform norm
temp[0][12:15],temp[1] # but we don't want label to get transformed

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), -2.52)

In [ ]:
type(t)

torch.Tensor

In [ ]:
@Transform
def norm(x:torch.Tensor,m,s): return (x-m)/s #type notation added: determine which of the tuple to apply tfm

In [ ]:
temp = norm(tupl,m=127,s=50)
temp[0][12:15],temp[1] # fixed!

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
           0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
           2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
           2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
           1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), 1)

# Semantic markers to existing type

In [ ]:
??TensorBase

In [ ]:
class MyTensorImg(TensorBase): pass # Note: why this extra step
# fastai wants to add 'semantic markers' to original type to represent 'different kinds of information' (such as to show using show()),
# aside from what the original type has to offer


In [ ]:
my_t = MyTensorImg(t)

In [ ]:
type(my_t),type(t)

(__main__.MyTensorImg, torch.Tensor)

In [ ]:
norm(t,m=127,s=50)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
norm(my_t,m=127,s=50)[12:15] # still works, as type notation will allow children of the type specified in the func

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
@Transform
def norm2(x:MyTensorImg,m,s): return (x-m)/s 

In [ ]:
norm2(t,m=127,s=50)[12:15] # not working, since torch.Tensor is not the same or children of MyTensorImg

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164., 239.,  26.,   0.,
           0.,   0.,   0.,  96., 236.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,  47.,   0.,   0.,
           0.,   0.,   0., 179., 235.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   8., 223., 222.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.]])

In [ ]:
norm2(my_t,m=127,s=50)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

# Inherit from Transform (to keep a state/attribute for your transformation)

Remember to 'encode'

In [ ]:
class Norm(Transform):
    def __init__(self,m,s):
        super().__init__()
#         store_attr(self,'m,s')
        self.m,self.s = m,s
    def encodes(self,x:torch.Tensor): return (x-self.m)/self.s
    def encodes(self,x: MyTensorImg): return (x-self.m)/self.s
    # add other type for encodes here if you want
    
    def decodes(self,x: MyTensorImg): return (x*self.s)+ self.m

In [ ]:
# equivalent, dynamically. TODO: need testing, since

# class Norm(Transform): pass

# @Norm
# def encodes(self,x:torch.Tensor,m,s): return (x-m)/s


In [ ]:
type(my_t),type(t)

(__main__.MyTensorImg, torch.Tensor)

In [ ]:
f = Norm(m=127,s=50)
f(my_t)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
f(t)[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.7400,  2.2400, -2.0200, -2.5400, -2.5400, -2.5400, -2.5400, -0.6200,
          2.1800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.3000, -1.6000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,  1.0400,
          2.1600, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,  1.9200,
          1.9000, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
my_t_norm = f(my_t)

In [ ]:
f.decodes(my_t_norm)[12:15]

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000, 164.0000, 239.0000,  26.0000,   0.0000,   0.0000,   0.0000,
           0.0000,  96.0000, 236.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,  12.0000,  47.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000, 179.0000, 235.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           8.0000, 223.0000, 222.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]])

# Multiple transform in one go = Pipeline

## option 1: use compose

In [ ]:
x = torch.arange(9).view(3,3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
torch.flip(x,[1])

tensor([[2, 1, 0],
        [5, 4, 3],
        [8, 7, 6]])

In [ ]:
@Transform
def flip_img(x:MyTensorImg): return torch.flip(x,[1]) # flip among axis 1

In [ ]:
f_norm =Norm(m=127,s=50)
f_compose = compose(f_norm,flip_img)

In [ ]:
temp = f_compose(my_t)
type(temp)

__main__.MyTensorImg

In [ ]:
temp[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
# but no decode
f_compose.decode

AttributeError: 'function' object has no attribute 'decode'

## option 2: use pipeline

In [ ]:
Pipeline??

In [ ]:
# note that Pipeline will convert everything into Transform, so no need for Transform annotation like in option 1

# @Transform: this is no need
def flip_img(x:MyTensorImg): return torch.flip(x,[1]) # flip among axis 1

In [ ]:
f_norm =Norm(m=127,s=50)

In [ ]:
p = Pipeline([f_norm,flip_img])
temp = p(my_t)
temp[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
type(temp) # Note that it keeps the original type, even though flip_img should technically output a torch tensor due to torch,flip

__main__.MyTensorImg

In [ ]:
type(p.decode(temp)) # decode keeps the original type too

__main__.MyTensorImg

In [ ]:
p.decode(temp)[12:15] # note that only f_norm decode is called. flip_img does not have decode

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 236.0000,  96.0000,   0.0000,
           0.0000,   0.0000,   0.0000,  26.0000, 239.0000, 164.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 235.0000, 179.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,  47.0000,  12.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000, 222.0000, 223.0000,   8.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]])

### With tuple

In [ ]:
type(my_t)

__main__.MyTensorImg

In [ ]:
my_t_tuple = (my_t,1)

In [ ]:
p = Pipeline([f_norm,flip_img])
temp = p(my_t_tuple)
temp[0][12:15],temp[1]

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  2.1800, -0.6200, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.0200,  2.2400,  0.7400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  2.1600,  1.0400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -1.6000, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400,  1.9000,  1.9200, -2.3800, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400]]), 1)

In [ ]:
p = Pipeline([f_norm,flip_img],as_item=True) # note again: as_item=True will force the input as a whole object. So this object is gonna be type 'Tuple'
temp = p(my_t_tuple)
temp[0][12:15],temp[1] #there is no encode(...,o:Tuple), so no transformation is performed

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164., 239.,  26.,   0.,
            0.,   0.,   0.,  96., 236.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,  47.,   0.,   0.,
            0.,   0.,   0., 179., 235.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   8., 223., 222.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.]]), 1)

# Specify output of function (not working)

In [ ]:
@Transform
def create_image_tensor(x): return tensor(array(load_image(x)))

In [ ]:
fn

PosixPath('/home/quantran/.fastai/data/mnist_tiny/train/7/9286.png')

In [ ]:
temp = create_image_tensor(fn)
type(temp)

torch.Tensor

In [ ]:
# specify/cast output type (NOT WORKING NOW)
@Transform
def create_image_tensor(x)->TensorImage: return tensor(array(load_image(x)))

In [ ]:
temp = create_image_tensor(fn)
type(temp) #TODO: that does not work... it should return local.torch_core.TensorImage

torch.Tensor

In [ ]:
TensorImage

local.torch_core.TensorImage